//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Developer
    {
        public Developer()
        {
            this.RegistrovanProizvods = new HashSet<RegistrovanProizvod>();
        }
    
        public int Id { get; set; }
        public string RacunID { get; set; }
    
        public virtual Nalog Nalog { get; set; }
        public virtual Racun Racun { get; set; }
        public virtual ICollection<RegistrovanProizvod> RegistrovanProizvods { get; set; }
    }
}
