//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        public Racun()
        {
            this.Developers = new HashSet<Developer>();
            this.Korisniks = new HashSet<Korisnik>();
        }
    
        public string Id { get; set; }
        public string Stanje { get; set; }
    
        public virtual ICollection<Developer> Developers { get; set; }
        public virtual ICollection<Korisnik> Korisniks { get; set; }
    }
}
